## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [9]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [11]:
# 1) Seu código aqui
questoes = [24, 18, 8, 8, 8, 12, 12]
assuntos = ['mat', 'por', 'geo', 'ing', 'his', 'fis', 'qui']
questoes_por_assunto = pd.Series(data = questoes, index = assuntos)

acertos_mat = df_mat / questoes_por_assunto['mat']
acertos_por = df_por / questoes_por_assunto['por']
acertos_geo = df_geo / questoes_por_assunto['geo']
acertos_ing = df_ing / questoes_por_assunto['ing']
acertos_his = df_his / questoes_por_assunto['his']
acertos_fis = df_fis / questoes_por_assunto['fis']
acertos_qui = df_qui / questoes_por_assunto['qui']

In [13]:
# 2) Seu código aqui
acertos_total = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui
acertos_total

    Qt_acertos
0           35
1           48
2           50
3           32
4           30
..         ...
95          34
96          27
97          40
98          40
99          42

[100 rows x 1 columns]

In [15]:
# 3) Seu código aqui
acertos_por_aluno = acertos_total / questoes_por_assunto.sum()
acertos_por_aluno

    Qt_acertos
0     0.388889
1     0.533333
2     0.555556
3     0.355556
4     0.333333
..         ...
95    0.377778
96    0.300000
97    0.444444
98    0.444444
99    0.466667

[100 rows x 1 columns]

In [17]:
# 4) Seu código aqui
alunos_sup_45 = len(acertos_total.loc[acertos_total['Qt_acertos'] > 45])
alunos_sup_45

31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [19]:
# seu código aqui
#2.1 - Desqualificados DataFrame
notas = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis = 1)
notas.columns = ['mat', 'por', 'geo', 'ing', 'his', 'fis', 'qui']
#notas
desqualificados = notas[(notas[['mat', 'fis', 'qui']] == 0).any(axis = 1)]
desqualificados

    mat  por  geo  ing  his  fis  qui
3    10    7    3    4    0    0    8
6     6    0    7    7    5    0    4
10   10    8    3    2    1    7    0
12   20    8    3    7    1    0    3
14    7   11    1    7    1    4    0
20   23   11    6    5    6    2    0
25    0    4    7    4    0    4    8
26   11   14    6    2    7    0    0
27   21   13    1    5    7    3    0
33   14    8    0    5    6    6    0
35   11   14    6    3    3    0   11
49    8    1    1    0    1    0    8
56    7    6    7    5    6    0    8
65    1    8    2    4    3    0    6
66    5    4    3    6    3    0   10
72   11   16    3    4    7    0    9
73    1   16    2    4    3    0   11
74    9   11    0    7    5    7    0
84   15    1    0    5    1    0    4
89   23   11    7    7    6    9    0
92   14   10    1    6    1    8    0
94    0    5    2    6    1    3    8
98    0   10    3    1    5   10   11

In [21]:
#2.2 - Desqualificados quantidade
len(desqualificados)

23

In [23]:
#2.3 - Média em história e geografia
media_his = round(desqualificados['his'].mean(), 2)
media_geo = round(desqualificados['geo'].mean(), 2)
print(f'Média História:', media_his)
print(f'Média Geografia:', media_geo)

Média História: 3.43
Média Geografia: 3.22

In [25]:
#2.4 - Dataframe alunos qualificados
qualificados = notas[(notas[['mat', 'fis', 'qui']] != 0).all(axis = 1)]
qualificados

    mat  por  geo  ing  his  fis  qui
0     6    7    7    3    1    8    3
1    19   10    0    0    0   11    8
2    14   16    0    5    7    4    4
4     7    2    2    7    0    9    3
5    20    2    5    3    2    9    9
..  ...  ...  ...  ...  ...  ...  ...
93   12   16    5    5    6    6    6
95    6    4    7    1    4    9    3
96    8    1    4    6    1    4    3
97   23    5    0    2    4    1    5
99   11   15    0    1    6    7    2

[77 rows x 7 columns]

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [27]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-17332d39-e31b-458a-b9a5-c838c55ef160.c000.csv'

In [29]:
# 1) Sua solução aqui
df_vacina = pd.read_csv(arquivo, sep=';')

In [30]:
df_vacina.head(3)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,d5a5990f-3e38-406d-865a-a5afa7e0d452-i0b0,93ad8645ae1ef18e1d0467375d542a9d4810e07c062a52...,43,1978-01-02,F,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,8.0,Trabalhadores da Educação,ABW4731,ASTRAZENECA,Organization/00394544000851,2021-06-07,1ª Dose,89,COVID-19 ASTRAZENECA - ChAdOx1-S,Novo PNI
1,50feb760-e85e-467c-b334-16b3f894284e-i0b0,0df34ce8d06fc0a97b86c0cb7fc226a7ceede21176161f...,16,2005-02-17,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FD7221,PFIZER,Organization/00394544000851,2021-08-13,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
2,b82f2476-9e24-4577-b494-eaa096853140-i0b0,0d18d7297e732160551a71e9df1b4ad0d35e4c0534a648...,45,1976-03-15,M,1,BRANCA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,215VCD116W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-06-24,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI

In [33]:
df_vacina.dtypes

document_id                                  object
paciente_id                                  object
paciente_idade                                int64
paciente_dataNascimento                      object
paciente_enumSexoBiologico                   object
paciente_racaCor_codigo                       int64
paciente_racaCor_valor                       object
paciente_endereco_coIbgeMunicipio           float64
paciente_endereco_coPais                    float64
paciente_endereco_nmMunicipio                object
paciente_endereco_nmPais                     object
paciente_endereco_uf                         object
paciente_endereco_cep                       float64
paciente_nacionalidade_enumNacionalidade     object
estabelecimento_valor                         int64
estabelecimento_razaoSocial                  object
estalecimento_noFantasia                     object
estabelecimento_municipio_codigo              int64
estabelecimento_municipio_nome               object
estabelecimento_uf                           object
vacina_grupoAtendimento_codigo                int64
vacina_grupoAtendimento_nome                 object
vacina_categoria_codigo                     float64
vacina_categoria_nome                        object
vacina_lote                                  object
vacina_fabricante_nome                       object
vacina_fabricante_referencia                 object
vacina_dataAplicacao                         object
vacina_descricao_dose                        object
vacina_codigo                                 int64
vacina_nome                                  object
sistema_origem                               object
dtype: object

In [35]:
#len(df_vacina)
vacinas_registradas, _ = df_vacina.shape
vacinas_registradas

388110

In [65]:
# 2) 
df_pacientes_vacinados = df_vacina['paciente_id'].nunique()
df_pacientes_vacinados

317139

In [67]:
# 3) 
primeira_dose_valor = df_vacina['vacina_descricao_dose'].unique()[0]
df_primeira_dose = df_vacina[df_vacina['vacina_descricao_dose'] == primeira_dose_valor]
df_primeira_dose['paciente_id'].nunique()

143330

In [69]:
# 3) solução alternativa
df_primeira_dose_alternativa = df_vacina['vacina_descricao_dose'].unique()[0]
#primeira_dose_alternativa
df_vacina['paciente_id'].loc[df_vacina['vacina_descricao_dose'] == primeira_dose_valor].nunique()

143330

In [73]:
# 4) 
df_menores = df_vacina[df_vacina['paciente_idade'] < 18]
df_menores['paciente_id'].nunique()

68713

In [77]:
# 5)
df_vacina['estabelecimento_razaoSocial'].nunique()

63

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [117]:
# 1) 
df_vacina_copia = df_vacina[df_vacina['paciente_idade'] < 18].copy()
df_vacina_copia.head(5)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
1,50feb760-e85e-467c-b334-16b3f894284e-i0b0,0df34ce8d06fc0a97b86c0cb7fc226a7ceede21176161f...,16,2005-02-17,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FD7221,PFIZER,Organization/00394544000851,2021-08-13,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
4,c009bd92-25e9-4fdd-8f27-725022b3d4dd-i0b0,8b92b11a7e330b8a8bf6119d04f8daf72fb30a7f81e10d...,14,2007-01-02,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FD7221,PFIZER,Organization/00394544000851,2021-08-13,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
8,be326d7c-dcde-400e-a701-b4ffed4039fe-i0b0,a7debef33553c6eabb36cd08eb6592761ef81e63766587...,12,2009-12-29,M,3,PARDA,352050.0,10.0,INDAIATUBA,...,2.0,Faixa Etária,220250,SINOVAC/BUTANTAN,152,2022-11-10,2ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
9,51d78810-e94e-4a49-84b4-c67d3922a356-i0b0,018bcc9fde47ed79da86fa34088d8fdaa871f69aabf991...,8,2013-06-05,M,3,PARDA,120030.0,10.0,FEIJO,...,NaN,NaN,FP1176,PFIZER,Organization/28290,2022-01-28,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
10,e590a0b2-dc59-49e0-a6c2-115e9410cf2c-i0b0,ccd2911169a073c71cd7144800c81c6391ad43c31df97f...,12,2010-02-09,F,1,BRANCA,120040.0,10.0,RIO BRANCO,...,NaN,NaN,FP8290,PFIZER - PEDI?TRICA,28290,2022-03-21,2ª Dose,99,COVID-19 PEDIÁTRICA - PFIZER COMIRNATY,Novo PNI

In [119]:
# 2) 
df_vacina_copia.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [121]:
# 3)
df_vacina_copia['vacina_categoria_nome'].value_counts()

vacina_categoria_nome
Faixa Etária                                      47910
Povos Indígenas                                    4724
Outros                                             3755
Povos e Comunidades Tradicionais                    874
Trabalhadores de Saúde                              264
Comorbidades                                         56
População Privada de Liberdade                       53
Gestantes                                            44
Trabalhadores da Educação                            14
Trabalhadores de Transporte                          13
Pessoas com Deficiência                              11
Pessoas Institucionalizadas                           3
Pessoas de 60 anos ou mais institucionalizadas        1
Puérperas                                             1
Name: count, dtype: int64

In [129]:
# 4)
colunas = ['estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf']
df_estabelecimento = df_vacina_copia.loc[:, colunas]
#df_estabelecimento.head()

In [139]:
# 5)
df_estabelecimento_dados = df_estabelecimento.drop_duplicates()
df_estabelecimento_dados.head()

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
13,2000504,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ILDA BARBOSA DE SOUZA,120080,PORTO ACRE,AC
16,2000016,PREFEITURA MUNICIPAL DE RODRIGUES ALVES,UNIDADE BASICA PADRE TEODORO ARNDS,120042,RODRIGUES ALVES,AC
21,6634230,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOSE PAULO DE SOUZA,120025,EPITACIOLANDIA,AC